### ISSUE TITLE
Primitive drawing

### ISSUE THREAD

**Issue by Frimkron** [Fiona/Myrmidon#42]
It would be nice if Myrmidon allowed you to create primitives such as lines, circles and rectangles. These would be objects that persisted, like Entities, and could be moved around the screen, rotated, scaled, etc. See Div2/Fenix/Bennu for [an example](http://wiki.bennugd.org/index.php?title=Draw_circle) of how this might work. Bennu returns a handle to the newly created object.

**Comment by Fiona** [comment]
Sorted
